# Generated by Django 4.1.7 on 2023-02-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Players",
            fields=[
                ("playerId", models.BigIntegerField(primary_key=True, serialize=False)),
                ("playerName", models.CharField(max_length=30)),
            ],
        ),
    ]
