# Generated by Django 4.1.7 on 2023-02-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_rename_players_player"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerFantasy",
            fields=[
                ("playerId", models.BigIntegerField(primary_key=True, serialize=False)),
                ("playerName", models.BigIntegerField(max_length=30)),
                ("playerFP", models.DecimalField(decimal_places=2, max_digits=8)),
                ("playerFPLast5", models.DecimalField(decimal_places=2, max_digits=8)),
                ("playerFPLast10", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
