import Head from 'next/head'
import Navbar from "../components/Navbar";
import styles from '@/styles/Home.module.css'
import { useAuth } from "../contexts/AuthContext";

export default function Home() {

  // Use the AuthContext to get values for the currentUser
  // and helper functions for logIn and logOut
  const { currentUser, logOut, logIn } = useAuth();

  return (
    <>
      <Head>
        <title>Fantasy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.container}>
        <button styles={styles.signIn} onClick={currentUser.addr ? logOut : logIn}>
          {currentUser.addr ? "Log Out" : "Login"}
        </button>
        <p>{currentUser.addr ? currentUser.addr : currentUser.addr}</p>
      </main>
    </>
  )
}
